from enum import Enum


class DisconnectionReasonEnum(Enum):

    RESTARTING = "RESTARTING"

    UNEXPECTED = "UNEXPECTED"

    SWITCHING_TO_GAME_SERVER = "SWITCHING_TO_GAME_SERVER"

    SWITCHING_TO_HUMAN_VENDOR = "SWITCHING_TO_HUMAN_VENDOR"

    DISCONNECTED_BY_POPUP_WITHOUT_RESET = "DISCONNECTED_BY_POPUP_WITHOUT_RESET"

    DISCONNECTED_BY_POPUP = "DISCONNECTED_BY_POPUP"

    DISCONNECTED_BY_USER = "DISCONNECTED_BY_USER"

    NEVER_CONNECTED = "NEVER_CONNECTED"

    WANTED_SHUTDOWN = "WANTED_SHUTDOWN"

    EXCEPTION_THROWN = "EXCEPTION_THROWN"

    CONNECTION_LOST = "CONNECTION_LOST"

    CHANGING_SERVER = "CHANGING_SERVER"

    CONNECTION_PROCESS_CRASHED = "CONNECTION_PROCESS_CRASHED"

    BANNED = "BANNED"

    CONNECTION_BLOCKED = "CONNECTION_BLOCKED"
